# Generated by Django 3.2.5 on 2022-12-15 13:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221213_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[home.models.validate_match_id])),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
    ]
